### ISSUE TITLE
name in the navigation drawer needs to be changed

### ISSUE THREAD

**Issue by iamvasuh** [opendatakit/skunkworks-bat#10]
![navdrawer](https://user-images.githubusercontent.com/42612183/53736043-a7aee780-3eae-11e9-9e00-b32e5ed6ba27.jpeg)

**Comment by iamvasuh** [comment]
@jbeorse  i think "ODK Notifications" should replace "Android Studio"

**Comment by jbeorse** [comment]
You are right that this is an issue, but I wouldn't name it "ODK Notifications" yet since the project is not officially released into the ODK tools yet and doesn't have an official name. As mentioned in [this comment](https://github.com/opendatakit/skunkworks-bat/pull/11#issuecomment-470976932), lets call it "Bat" for now.

**Comment by iamvasuh** [comment]
ok @jbeorse i will just change it to "Bat"

**Comment by jbeorse** [comment]
Resolved with https://github.com/opendatakit/skunkworks-bat/pull/11
